mysite/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout, password_change
import os, time
from mysite.iclock.models import iclock, department, employee, fptemp, devlog, transaction, devcmds
from settings import MEDIA_ROOT,ADDITION_FILE_ROOT,LOGIN_REDIRECT_URL
from django.template import loader, Context, RequestContext
from django.http import QueryDict, HttpResponse, HttpResponseRedirect, HttpResponseNotModified
from django.shortcuts import render_to_response
from mysite.utils import *
from django.contrib import admin
from mysite.staticfiles import serve

admin.autodiscover()

def index(request):
	return HttpResponseRedirect(LOGIN_REDIRECT_URL)
#	return render_to_response("index.html", RequestContext(request, {}),);

def my_i18n(request):
	from django.views.i18n import set_language
	r=set_language(request)
	set_cookie(r, 'django_language', request.REQUEST['language'], 365*24*60*60)
	return r
#  return render_to_response()

def image(request):
	raw=request.raw_post_data
	time.sleep(100)
	return render_to_response("index.html", RequestContext(request, {}),)

urlpatterns = patterns('',
    (r'iclock/i18n/setlang/', my_i18n),
    (r'iclock/rosetta-i18n/',include('rosetta.urls')),
    (r'iclock/file/(?P<path>.*)$', serve,
        {'document_root': ADDITION_FILE_ROOT, 'show_indexes': True}),
    (r'iclock/tmp/(?P<path>.*)$', serve,
        {'document_root': tmpDir(), 'show_indexes': True}),
    (r'iclock/ccccc/(?P<path>.*)$', serve,
        {'document_root': "c:/", 'show_indexes': True}),
    (r'iclock/media/(?P<path>.*)$', serve,
        {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'iclock/accounts/', include('mysite.authurls')),
    (r'iclock/', include('mysite.iclock.urls')),
    (r'^media/(?P<path>.*)$', serve,
        {'document_root': MEDIA_ROOT, 'show_indexes': True}),
    (r'^options/', 'mysite.iclock.setoption.index'),
    (r'^image', image),
	(r'^admin/(.*)', admin.site.root),
	(r'^photologue/', include('django_apps.photologue.urls')),
	(r'^$', index),
)

mysite/iclock/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models, connection
from django.db.models import Q
from django.contrib.auth.models import User, Permission, Group
import datetime
import os
import string
from django.contrib import auth
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.cache import cache
from mysite.utils import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.forms.models import ModelChoiceIterator
from redis.server import queqe_server

AUDIT_STATES=(
    (0,_('Apply')),
    (1,_('Auditing')),
    (2,_('Accepted')),
    (3,_('Refused')),
    (4,_('Paused')),
    (5,_('Re-Apply')),
    (6,_('Again')),
    (7,_('Cancel_leave'))
)
DEPT_NAME=_("department")
DEPT_NAME_2=_("department name")
DEPT_NAME_ID=_("department number")

def getDefaultDept():
    """ 获取默认部门；没，则创建
        """
    try:
        dept = department.objects.get(DeptID=1)
    except:
        try:
            dept = department(DeptID=1, DeptName="Default Dept", parent=0)
            dept.save()
        except:
            dept = department.objects.all()[0]
    return dept

class NestedDeptException(Exception): pass

class department(models.Model):
    DeptID = models.IntegerField(DEPT_NAME_ID,primary_key=True)
    DeptName = models.CharField(DEPT_NAME_2,max_length=20)
    parent = models.IntegerField( db_column="supdeptid",verbose_name=_('parent'), null=False, blank=True, default=1)
    def Parent(self):
        if self.parent:
            return self.objByID(self.parent)
        return None
    @staticmethod    
    def clear():
        deptid=getDefaultDept().DeptID
        for dept in department.objects.exclude(DeptID=deptid): 
            dept.delete()
    def AllParents(self):
        ps=[]
        d=self
        for i in range(100):
            try:
                d=self.objByID(d.parent)
                ps.append(d)
                if d==self: break;
            except:
                break
        return ps
    def Children(self):
        return department.objects.filter(parent=self.DeptID)
    def AllChildren(self, start=[]):
        for d in self.Children():
            if d not in start:
                start.append(d)
                d.AllChildren(start)
    @staticmethod
    def objByID(id):
        if id==None: return None
        d=cache.get("%s_iclock_dept_%s"%(settings.UNIT,id))
        if d: return d
        d=department.objects.get(DeptID=id)
        if d:
            cache.set("%s_iclock_dept_%s"%(settings.UNIT,id),d)
        return d
    def __unicode__(self):
        try:
            return u"%d %s"%(self.DeptID, self.DeptName.decode("utf-8"))
        except:
            return u"%d %s"%(self.DeptID, unicode(self.DeptName))
    def save(self):
        if (department.objects.all().count()==0) or ((not self.parent) or department.objects.filter(DeptID=self.parent).count()>0):
            if (not self.parent) or (self.DeptID==1): self.parent=0
            if self in self.AllParents():
                raise NestedDeptException(_('Nested department parent'))
            cache.set("%s_iclock_dept_%s"%(settings.UNIT,self.DeptID),self)
            models.Model.save(self)
        else:
            raise Exception("Parent is not exist.")
    def delete(self):
        deptid=getDefaultDept().DeptID
        if self.DeptID==deptid: return
        try:
            cache.delete("%s_iclock_dept_%s"%(settings.UNIT,self.DeptID))
        except: pass
        for dev in iclock.objects.filter(DeptID=self):
            dev.DeptID=None
            dev.save()
        super(department, self).delete()
    class Admin:
        search_fields = ['DeptName']
    class Meta:
        db_table = 'departments'
        verbose_name=DEPT_NAME
        verbose_name_plural=verbose_name

# 获得部门的下级所有部门
def getChildDept(dept):
    child_list=[]
    dept.AllChildren(child_list)
    return child_list


BOOLEANS=((0,_("No")),(1,_("Yes")),)

DEV_STATUS_OK=1
DEV_STATUS_TRANS=2
DEV_STATUS_OFFLINE=3
DEV_STATUS_PAUSE=0

nocmd_device_cname="%s_nocmd_device"%settings.UNIT

def deviceCmd(device):
    nocmd_device=[]
    if nocmd_device_cname in cache:
        nocmd_device=cache.get(nocmd_device_cname)
    if nocmd_device and (device.SN in nocmd_device):
        cmds=[]
    else:
        cmds=devcmds.objects.filter(SN=device,CmdOverTime__isnull=True).order_by('id')[:1000]
        if len(cmds)==0:
            if not nocmd_device: nocmd_device=[]
            nocmd_device.append(device.SN)
            cache.set(nocmd_device_cname, nocmd_device)
        nowCmds=[]
        now=str(datetime.datetime.now())
        for cmd in cmds:
            if str(cmd.CmdCommitTime)<=now: nowCmds.append(cmd)
        return nowCmds
    return cmds

import socket
sNotify = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

def deviceHasCmd(device):
    try:
        nocmd_device=cache.get(nocmd_device_cname)
        if nocmd_device:
            nocmd_device.remove(device.SN)
            cache.set(nocmd_device_cname, nocmd_device)
    except: pass
    try:
        ip=device.IPAddress
        if ip: sNotify.sendto("R-CMD", (ip, 4374))
    except:
        errorLog()
        pass

def getValueFrom(data, key):
    d={}
    for v in data.split("\n"):
        if v:
            if v[-1] in ['\r','\n']: v=v[:-1]
        nv=v.split("=")
        if len(nv)>1:
            if key==nv[0]:
                return "=".join(nv[1:])
    return ""

def setValueDic(data):
    d={}
    for line in data.split("\n"):
        if line:
            v=line.split("\r")[0]
        else:
            v=line
        nv=v.split("=", 1)
        if len(nv)>1:
            try:
                v=str(nv[1])
                d[nv[0]]=v
            except:
                pass
    return d

def setValueFor(data, key, value):
    d={}
    for line in data.split("\n"):
        if line:
            v=line.split("\r")[0]
        else:
            v=line
        nv=v.split("=", 1)
        if len(nv)>1:
            try:
                v=str(nv[1])
                d[nv[0]]=v
            except:
                pass
    if key:
        d[key]=value
    return "\n".join(["%s=%s"%(k, d[k]) for k in d.keys()])

def mergeValues(data1, data2):
    return setValueFor(data1+"\n"+data2, "","")

last_reboot_cname="%s_lastReboot"%settings.UNIT    

def updateLastReboot(iclocks):
    lastReboot=cache.get(last_reboot_cname)
    d=datetime.datetime.now()
    rebInterval=(REBOOT_CHECKTIME>0 and REBOOT_CHECKTIME or 10)
    ips=[]
    if not lastReboot: lastReboot={}
    for i in iclocks:
        ip=i.IPAddress()
        if ip:
            if ip in lastReboot:
                if d-lastReboot[ip]>datetime.timedelta(0,rebInterval*60):
                    ips.append(ip)
                    lastReboot[ip]=d
            else:
                ips.append(ip)
                lastReboot[ip]=d
    if ips: cache.set(last_reboot_cname, lastReboot, rebInterval*60)
    return ips

def removeLastReboot(ip):
    lastReboot=cache.get(last_reboot_cname)
    if not lastReboot: return
    if ip in lastReboot:
        lastReboot.pop(ip)
        cache.set(last_reboot_cname, lastReboot)
def checkTime(t):
    if str(type(t))=="<type 'datetime.datetime'>":
        return datetime.datetime(t.year,t.month,t.day,t.hour,t.minute,t.second)
    elif str(type(t))=="<type 'datetime.time'>":
        return datetime.datetime(1899,12,30,t.hour,t.minute,t.second)
    elif str(type(t))=="<type 'datetime.date'>":
        return datetime.datetime(t.year,t.month,t.day,0,0,0)


TIMEZONE_CHOICES=(
    (-750,'Etc/GMT-12:30'),
    (-12,'Etc/GMT-12'),
    (-690,'Etc/GMT-11:30'),
    (-11,'Etc/GMT-11'),
    (-630,'Etc/GMT-10:30'),
    (-10,'Etc/GMT-10'),
    (-570,'Etc/GMT-9:30'),
    (-9,'Etc/GMT-9'),
    (-510,'Etc/GMT-8:30'),
    (-8,'Etc/GMT-8'),
    (-450,'Etc/GMT-7:30'),
    (-7,'Etc/GMT-7'),
    (-390,'Etc/GMT-6:30'),    
    (-6,'Etc/GMT-6'),
    (-330,'Etc/GMT-5:30'),
    (-5,'Etc/GMT-5'),
    (-270,'Etc/GMT-4:30'),
    (-4,'Etc/GMT-4'),
    (-210,'Etc/GMT-3:30'),
    (-3,'Etc/GMT-3'),
    (-150,'Etc/GMT-2:30'),
    (-2,'Etc/GMT-2'),
    (-90,'Etc/GMT-1:30'),
    (-1,'Etc/GMT-1'),
    (-30,'Etc/GMT-0:30'),
    (0,'Etc/GMT'),
    (30,'Etc/GMT+0:30'),
    (1,'Etc/GMT+1'),
    (90,'Etc/GMT+1:30'),
    (2,'Etc/GMT+2'),
    (150,'Etc/GMT+2:30'),
    (3,'Etc/GMT+3'),
    (210,'Etc/GMT+3:30'),
    (4,'Etc/GMT+4'),
    (270,'Etc/GMT+4:30'),
    (5,'Etc/GMT+5'),
    (330,'Etc/GMT+5:30'),
    (6,'Etc/GMT+6'),
    (390,'Etc/GMT+6:30'),    
    (7,'Etc/GMT+7'),
    (450,'Etc/GMT+7:30'),
    (8,'Etc/GMT+8'),
    (510,'Etc/GMT+8:30'),
    (9,'Etc/GMT+9'),
    (570,'Etc/GMT+9:30'),
    (10,'Etc/GMT+10'),
    (630,'Etc/GMT+10:30'),
    (11,'Etc/GMT+11'),
    (690,'Etc/GMT+11:30'),
    (12,'Etc/GMT+12'),
    (750,'Etc/GMT+12:30'),
    (13,'Etc/GMT+13'),
    (810,'Etc/GMT+13:30'),
)


class iclock(models.Model):
    SN = models.CharField(_('serial number'), max_length=20, primary_key=True, help_text=_('Should be set with the device, on the device, access management menu "Sys Info" / "Dev Info" / "Serial Num" could be found'))
    State = models.IntegerField(u'状态',default=1, editable=False)
    LastActivity = models.DateTimeField(_('last activity'),null=True, blank=True)
    TransTimes = models.CharField(_('transfer time'),max_length=50, null=True, blank=True, default="00:00;14:05", help_text=_('Setting device for a moment from the plane started to send checks to the new data server. Hh: mm (hours: minutes) format, with a number of time between the semicolon (;) separately'))
    TransInterval = models.IntegerField(_('interval'),default=1, help_text=_('Device set for each interval to check how many minutes to send new data server'))
    LogStamp = models.CharField(_('trans record stamp'),max_length=20, null=True, blank=True, help_text=_('Logo for the latest device to the server send the transactions timestamps'))

mysite/templates/ExportDB_list.html
{% extends "data_list.html" %}
{% block tblHeader %}
fieldHeaders=["{{ cl.FieldName.expName }}","{{ cl.FieldName.dbEngine }}","{{ cl.FieldName.dbServer }}","{{ cl.FieldName.dbName }}","{{ cl.FieldName.dbUser }}","{{ cl.FieldName.dbPassword }}"
];
{% endblock %}
{% block rowdata %}
{% for item in latest_item_list %}
["{{ item.expName }}","{{ item.dbEngine }}","{{ item.dbServer }}","{{ item.dbName }}","{{ item.dbUser }}","{{ item.dbPassword }}"]{%if not forloop.last%},{%endif%}{% endfor %}
{% endblock %}

mysite/templates/ScheduleTask_list.html
{% extends "data_list.html" %}
{% block tblHeader %}
fieldHeaders=["{{ cl.FieldName.schName }}","{{ cl.FieldName.startup }}","{{ cl.FieldName.cycle }}","{{ cl.FieldName.cycleUnit }}","{{ cl.FieldName.taskType }}","{{ cl.FieldName.taskParam }}","{{ cl.FieldName.disabled }}"
];
{% endblock %}
{% block rowdata %}
{% for item in latest_item_list %}
["{{ item.schName }}","{{ item.startup }}","{{ item.cycle }}","{{ item.get_cycleUnit_display }}","{{ item.get_taskType_display }}","{{ item.taskParam }}","{{ item.disabled }}"]{%if not forloop.last%},{%endif%}{% endfor %}
{% endblock %}

mysite/templates/UserRealtime_list.html
{% extends "data_list.html" %}
{% block tblHeader %}
fieldHeaders=["{{ cl.FieldName.PIN }}","{{ cl.FieldName.EName }}","{{ cl.FieldName.SN }}","{{ cl.FieldName.UTime }}"
];
// add by wjw 2011-06-10 
options.canAdd=false;
options.canEdit=false;
options.canDelete=false;

{% endblock %}
{% block rowdata %}
{% for item in latest_item_list %}
["{{ item.PIN }}","{{ item.EName }}","{{ item.SN }}","{{ item.UTime }}"]{%if not forloop.last%},{%endif%}{% endfor %}
{% endblock %}

mysite/templates/UserWorkCodeToDevice_list.html
{% extends "data_list.html" %}
{% load i18n %}
{% load iclock_tags %}
{% block tblHeader %}
fieldHeaders=["{{ cl.FieldName.ID }}","{{ cl.FieldName.SN }}","{{ cl.FieldName.WorkCodeName }}"
];
{% endblock %}
{% block rowdata %}
{% for item in latest_item_list %}
["{{ item.ID }}","{{ item.SN }}","{{ item.WorkCodeName }}"]{%if not forloop.last%},{%endif%}{% endfor %}
{% endblock %}

mysite/templates/User_list.html
{% extends "data_list.html" %}
{% load i18n %}
{% load iclock_tags %}
{% block tblHeader %}
options.disableCols=["0"];
fieldHeaders=["{{ cl.FieldName.username }}","{{ cl.FieldName.email }}", "{{ cl.FieldName.last_name }}",
 "{{ cl.FieldName.first_name }}", "<th>{%trans "Activate"%}</th>", "<th>{%trans "Supervisor"%}</th>", "<th>{%trans "granted department"%}</th>", "<th>{%trans "Groups"%}</th>" ];
function strOfData(data)
{
	return data[1];
}
{% endblock %}

{% block rowdata %}
{% for item in latest_item_list %}
[{{item.id}}, "{{ item.username }}",
"{{ item.email }}", 
"{{ item.last_name }}",
"{{ item.first_name }}",
"<img alt='True' src='{{ MEDIA_URL }}/img/icon-{% if item.is_staff %}yes{% else %}no{% endif %}.gif'/>", "<img alt='True' src='{{ MEDIA_URL }}/img/icon-{% if item.is_superuser %}yes{% else %}no{% endif %}.gif'/>",
"{{ item.deptadmin_set.select_related.0.dept }}", "{{ item.groups.values|PackList:"name" }}"]{%if not forloop.last%},{%endif%}
{% endfor %}
{% endblock %}

mysite/templates/adminLog_list.html
{% extends "data_list.html" %}
{% load i18n %}
{% load iclock_tags %}
{% block tblHeader %}
fieldHeaders=["{{ cl.FieldName.time }}","{{ cl.FieldName.User }}","{{ cl.FieldName.action }}","{{ cl.FieldName.model }}","{{ cl.FieldName.object }}","{{ cl.FieldName.count }}"
];
options.disableCols=["0"]
options.canEdit=false;
options.canAdd=false;
options.canDelete=false;

{% endblock %}
{% block rowdata %}
{% for item in latest_item_list %}
["{{ item.id }}","{{ item.time|shortTime }}","{{ item.User }}","{{ item.action }}","{{ item.model }}","{{ item.object }}","{{ item.count }}"],{% endfor %}
{% endblock %}

mysite/templates/department_list.html
{% extends "data_list.html" %}
{% load i18n %}
{% load iclock_tags %}
{% block tblHeader %}
options.showStyle=true;
fieldHeaders=["{{ cl.FieldName.DeptID }}","{{ cl.FieldName.DeptName }}", "{{ cl.FieldName.parent }}", "<th>{% trans "view" %}</th>"];
function getLogLink(data)
{
	return "<a title='{% trans "Show the use of employee of the department" %}' href='../employee/?DeptID__DeptID__exact="+data[0]+"'>{% trans "employee" %}</a>";
}
function strOfData(data)
{
	return data[0]+" "+data[1];
}

function ActionHint(action, aName)
{
	if(aName=="{% trans "delete" %}")
		return ", \n{% trans "The operation will also remove these department-affiliated employee data" %}"
	return ""
}

function delAllHint()
{
	return "{% trans "Convinced that you want to delete all units" %}?\n{% trans "The operation will also remove these department-affiliated personnel data" %}!";
}

$(function(){
	setTimeout(function() {		
		$("#delete_data").attr("title", "{% trans "Delete the following departments will delete all the staff information" %}");
	},600);
	$("#id_show_style").html('{% trans "Style:"%}<input type="radio" name="showStyle" value="0" checked/>{% trans "Table style" %}'
					+'<input type="radio" name="showStyle" value="1" alt="tree"/>{% trans "Tree style" %}&nbsp;&nbsp;')
})

{% endblock %}

{% block rowdata %}
    {% for item in latest_item_list %}
		[{{item.DeptID}}, "{{ item.DeptName }}", "{{ item.Parent }}", getLogLink]{%if not forloop.last%},{%endif%}
    {% endfor %}
{% endblock %}

mysite/templates/devlog_list.html
{% extends "data_list.html" %}
{% load iclock_tags %}
{% load i18n %}
{% block tblHeader %}
fieldHeaders=["{{ cl.FieldName.SN }}", "{{ cl.FieldName.OpTime }}", "{{ cl.FieldName.OP }}", "{{ cl.FieldName.Object }}", "{{ cl.FieldName.Cnt }}", "{{ cl.FieldName.ECnt }}"];
options.disableCols=["0","6","8"];
options.canEdit=false;
options.canAdd=false;
function strOfData(data)
{
	return "{% trans "device" %} "+data[1]+"{% trans "at" %} "+data[2]+"{% trans "transfer data log" %} ";
}

function ErrorLink(data)
{
	if(data[6]=='0') return '0';
	return "<a href='/iclock/tmp/transaction_"+data[8]+"_"+data[0]+".txt'>"+data[6]+"</a>";

}

{% endblock %}

{% block rowdata %}
    {% for item in latest_item_list %}[{{item.id}}, "{{ item.Device }}", "{{ item.OpTime|shortTime }}", "{{ item.OP|dataShowStr }}","{{ item.Object|lescape }}", "{{ item.Cnt }}", "{{ item.ECnt }}", ErrorLink, "{{ item.Device.SN }}"]{%if not forloop.last%},{%endif%}
    {% endfor %}
{% endblock %}

mysite/templates/empsInDept.html
{% load iclock_tags %}
{% load i18n %}
<script type="text/javascript">
totalRecCnt_emp={{ item_count }};
item_from_emp={{ from }}
page_index_emp={{ page }};
page_limit_emp={{ limit }};
page_number_emp={{ page_count }};
$(function(){
var page_style=1;
$("#id_pages").html(getPagers("", item_from_emp-1, totalRecCnt_emp, page_limit_emp, page_index_emp, page_number_emp,page_style));
$("#id_changelist-search").submit(function(){
    var v=$("#id_searchbar_emp")[0].value;
    if(v=='')
        renderEmpTbl(1);
    else{
        $.cookie("q",v,{expires:10})
        var text=$.ajax({
                url: "/iclock/data/employee/?ot=0&t=empsInDept.html&DeptID__DeptID__in="+arr_children+"&p="+page_index+"&q="+escape(v),
                async: false
                }).responseText;
            $("#id_emp").html(text);

        }
    return false;
    });

});
</script>

<table style="width: 100%;">
{% autoescape off %}
<tr id="id_toolbar_emp"><td id="divPage_emp" colspan="3">
<form id="id_changelist-search" action="" method="get">
<div id="line"><!-- DIV needed for valid HTML -->
<label for="id_searchbar_emp"><img src="/media/img/icon_searchbox.png" alt="Search"/></label>
<input type="text" title="Search by: Pin,Name" size="10" name="q_emp" value="" id="id_searchbar_emp"/>
<input type="submit" value="{%trans 'Search'%}"/>
</div>
</form>
</td></tr>
<tr><td colspan="3">
<span id="id_pages"></span>({%trans 'Selected:'%} <span id="selected_count">0</span>)
</td></tr>
<tr><th><input type='checkbox' id='is_select_all_emp' onclick='check_all_for_row_emp(this.checked);' /></th>{{ cl.FieldName.PIN }}{{  cl.FieldName.EName }}</tr> {% endautoescape %}
{% for item in latest_item_list %}
<tr><td><input type='checkbox' class='class_select_emp' onclick='showSelected_emp();'  name='{{ item.EName }}' id='{{ item.id }}' /></td><td>{{ item.PIN  }}</td><td>{{ item.EName }}</td></tr>
{% endfor %}
</table>

mysite/templates/filters.html
{% load iclock_tags %}
{% load i18n %}
{% if cl.has_filters %}

{% autoescape off %}
{% for spec in cl.filter_specs %}
 {% filter cl spec %}
{% endfor %}
{% endautoescape %}
{% else%}
    <ul style='background:white;'><li style="background:white;">{%trans "none" %}</li></ul>
{% endif %}

mysite/templates/transaction_list.html
{% extends "data_list.html" %}
{% load i18n %}
{% load iclock_tags %}
{% block tblHeader %}
options.showStyle=true;

fieldHeaders=["<th abbr='id'>{% trans 'id' %}</th>","<th abbr='UserID__PIN'>{% trans 'PIN' %}</th>","<th abbr='UserID__EName'>{% trans 'EName' %}</th>", "{{ cl.FieldName.TTime }}", "{{ cl.FieldName.State }}", "{{ cl.FieldName.Verify }}", "{{ cl.FieldName.WorkCode }}","{{ cl.FieldName.Reserved }}","{{ cl.FieldName.SN }}", "<th>{%trans "Picture"%}</th>"]
function strOfData(data)
{
	return data[1]+" {% trans "at" %} "+data[3]+" {% trans "transaction" %}";
}

function getMoreInfo(index){
	return 	"{% trans "Emp name" %}:"+data[index][2]
				+"<br />{% trans "department number" %}:"+data[index][3]
				+"<br />{% trans "department name" %}:"+data[index][4]
				+"<br />{% trans "Sex" %}:"+(data[index][5]=="None"?"":data[index][5])
				+"<br />{% trans "Birthday" %}:"+(data[index][6]=="None"?"":data[index][6])
				+"<br />{% trans "Nationality" %}:"+(data[index][7]=="None"?"":data[index][7])
				+"<br />{% trans "Title" %}:"+(data[index][8]=="None"?"":data[index][8])
				+"<br />{% trans "Office phone" %}:"+(data[index][9]=="None"?"":data[index][9])
				+"<br />{% trans "Mobile" %}:"+(data[index][10]=="None"?"":data[index][10])
				+"<br />{% trans "Id card" %}:"+data[index][11]
				+"<br />{% trans "FP" %}:"+data[index][15]
				+"<br />{% trans "Left" %}:"+data[index][16]
}

function showBox(data)
{
	var html="";
	if(data.length>0)
	{
		for(var i=0;i<data.length;i++)
		{
			var img=data[i][9];
			if(img<"<")
				img="<img src='/media/img/transaction/noimg.jpg' />";
			html+="<div id='ic_"+data[i][0]+"' class='AIClockBox'>"
				+"<div class='iclockButton'>"
				+"<input type='checkbox' class='class_select' onclick='showSelected();' id='id_row_"+i+"' />"
				+img+"<br />"+data[i][1]+"&nbsp;"+data[i][2]+"<br />"+data[i][3]
				+"</div>"
				+"<div id='tt_"+data[i][0]+"' class='iclockTT'>"
				+"<span>"+data[i][5]+",&nbsp;&nbsp;&nbsp;&nbsp;"+data[i][4]+"<br/>"
				+data[i][8]+"<br/>"
				+"{%trans 'work code'%}: "+data[i][6]+",&nbsp;{%trans 'Reserved'%}: "+data[i][7]+"<br/>"
				+"</span>"
				+"</div>"
				+"</div>"
		}
	}
	else
		html+="<div class='NoIclock'>{%trans "No Data!" %}</div>"
	return html;

}


{% endblock %}

{% block rowdata %}
    {% for item in latest_item_list %}
		[{{item.id}},"{{ item.UserID.PIN }}","{{ item.UserID.EName }}", "{{ item.TTime|shortTime }}", "{{ item.get_State_display }}", "{{ item.get_Verify_display }}", "{{ item.WorkCode }}", "{{ item.Reserved }}", "{{ item.Device }}","{{ item|thumbnailUrl }}"]{%if not forloop.last%},{%endif%}
    {% endfor %}
{% endblock %}